### ISSUE TITLE
v1.0.0 Roadmap

### ISSUE THREAD

**Issue by natemoo-re** [natemoo-re/clack#35]
Infrastructure
- [ ] Testing (Vitest, needs to expose `input` and `output` to each prompt to mock)
- [ ] CI improvements
- [ ] More examples

Stability:
- [ ] Windows compat audit
- [ ] #20

Features:
- [ ] Additional Primitives
  - [ ] Grouped multiselect (Changesets-style)
  - [ ] Multiline text
  - [ ] Autocomplete / List search
  - [ ] File search?
- [ ] Prompt groups (like `prompts` / `inquirer`, but tree-shakeable)
- [ ] Improved Hooks #22

**Comment by itpropro** [comment]
Any updates @natemoo-re ? Would love to use the autocomplete.
Is there anything you need help with to progress on v1?

**Comment by natemoo-re** [comment]
In the interest of stability for existing `v0` users, [we've decided to switch `main` over to `v1.0.0-alpha.0`](https://github.com/bombshell-dev/clack/pull/250) and will be implementing new features on as part of the alpha release line.

Hoping to backport any critical bug fixes to the [`v0`](https://github.com/bombshell-dev/clack/tree/v0) releases, but no new minor releases.

**Comment by dreyfus92** [comment]
@itpropro the autocomplete #288  has been merged.

**Comment by ashleydavis** [comment]
Love this project and I'm keen to use it. Just wondering about the status of the `progress` component, will it be included in a  release soon?

**Comment by 43081j** [comment]
you should be able to install the 1.x alpha (`npm i @clack/prompts@alpha`), which has the progress prompt

its unlikely we will port those back to 0.x i think, but 1.x should actually be fairly stable if you want to try it 👍

**Comment by ashleydavis** [comment]
> you should be able to install the 1.x alpha (`npm i @clack/prompts@alpha`), which has the progress prompt

Oh thanks so much! I wish had I noticed that much earlier.

> 
> its unlikely we will port those back to 0.x i think, but 1.x should actually be fairly stable if you want to try it 👍

I've already tried it. Given that I hadn't noticed the alpha version I pulled your entire codebase into my monorepo and used it directly ;)  Was just a test run anyway and I'll undo that, next step will be to install the alpha version and use that.

But yeah it's great so far, thanks for your work.

**Comment by gstamp** [comment]
I think I might have hit a bug in the autocomplete. If I specify an `initialValue` option I end up getting this error: `TypeError: t.toLowerCase is not a function`

**Comment by 43081j** [comment]
This should be fixed already in main, or at least in #334 

Can you try the pkg.pr.new install from that pr? And see if you still get the error

**Comment by gstamp** [comment]
> Can you try the pkg.pr.new install from that pr? And see if you still get the error

Can confirm that it works. Sorry for the noise.

**Comment by 43081j** [comment]
no worries, thanks for checking! we will try get a new alpha released soon

**Comment by gstamp** [comment]
> no worries, thanks for checking! we will try get a new alpha released soon

Thanks. I did notice something strange when I tried to test the version from `pkg.pr.new` with with one of my apps. It's a commander.js cli app and when I was trying to run various commands it was showing the CLI from `knip` instead of the running my apps commands. Not sure what was going on there and didn't have much time to look into it today. I don't use `knip` in my application at all.

**Comment by dreyfus92** [comment]
@natemoo-re can you give this a last review, cause i'm trying to figure out what we missing for clack's stable release 👀 also cc. @43081j

**Comment by NullVoxPopuli** [comment]
> testing

does this mean https://github.com/bombshell-dev/clack/blob/main/packages/prompts/test/test-utils.ts will become public api?

How do CLI authors test their projects?

**Comment by 43081j** [comment]
these are not currently exported anywhere useful but you raise a good point, so we will try fit them into 1.0 👍 

ill have a think about it today, and how we can better document testing
